### ISSUE TITLE
Include environment name in notification

### ISSUE THREAD

**Issue by chrislennon** [gaymers-discord/discord-webook-notifier#5] opened 2017-06-13 09:00 UTC
Messages do not include the application name, sample messages below.

```
Environment health has transitioned from Ok to Info. Configuration update in progress (running for 3 seconds).
```

```
Environment health has transitioned from Info to Severe. Configuration update completed 13 seconds ago and took 69 seconds. None of the instances are sending data.
```

```
Environment health has transitioned from Severe to Ok.
```

**Comment by ThomasShaped** [comment] 2017-06-13 09:01
Dupe of #4 lol

**Closed** 2017-06-13 09:55 UTC
